spring:
  application:
    name: blogProject

  datasource:
    url: jdbc:mysql://localhost:3308/mysqldb
    username: minjin
    password: 1024
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true