spring:
  application:
    name: blogProject

  datasource:
    url: jdbc:mysql://localhost:3308/newDB
    username: minjin
    password: 1024
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

jwt:
  secretKey: 12345678901234567890123456789012
  refreshKey: 12345678901234567890123456789012

server:
  servlet:
    session:
      timeout: 60m